// const C = document.querySelector('#clears')
//     button.addEventListener('click', function())
const seven = document.querySelector("#7")
console.log(7)
// const screen = document.querySelector("#screen")
// const eight = document.querySelector("#8")
// const nine = document.querySelector ("#9")
// const divide = document.querySelector("#divide")
// const four = document.querySelector("#4")
// const five = document.querySelector("#5")
// const six = document.querySelector("#6")
// const timez = document.querySelector("#timez")
// const one = document.querySelector("#1")
// const two = document.querySelectory("#2")
// const three = document.querySelector("#3")
// const minus = document.querySelector("#minus")
// const zero = document.querySelector("#0")
// const decimal = document.querySelector("#decimal")
// const equal = document.querySelector("#equal")
// const plus = document.querySelector("#plus")

